# -*- coding: utf-8 -*-

SOCKETIO_DEFAULT_NSP = '/socket.io.default'

DEFAULT_PER_PAGE = 20

MIN_PASSWORD_LEN = 6
MAX_PASSWORD_LEN = 16
ADMIN_TOKEN_TAG = 'admin'
ADMIN_LOGIN_VALID_DAYS = 7

WX_USER_COOKIE_KEY = 'wx_user'
WX_USER_LOGIN_VALID_DAYS = 100
