# -*- coding: utf-8 -*-

SOCKETIO_DEFAULT_NSP = '/socket.io.default'

DEFAULT_PER_PAGE = 20

ADMIN_TOKEN_TAG = 'admin'
ADMIN_TOKEN_VALID_DAYS = 7

MIN_PASSWORD_LEN = 6

WX_USER_COOKIE_KEY = 'wx_user'
WX_USER_COOKIE_VALID_DAYS = 30
